[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".venv",
]

# Same as Black.
line-length = 120
indent-width = 4

[ai_model]
api_url = "https://api.deepseek.com"
model_v = "deepseek-chat"

[currency_reader]
starting_currency = "USD"